# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

parameters:
- name: hostArch
  type: string
  default: x86
- name: targetPlatform
  type: string
- name: vsDevCmdArch
  type: string
- name: buildOutputLocationVar
  type: string
  default: buildOutputLocation
- name: numShards
  type: number
  default: 8
jobs:
- job: 'test_${{ parameters.targetPlatform }}'
  pool: Arm2
  variables:
    fixedFlags: '--timeout=240;--shuffle'
    parallelismFlag: '-j$(testParallelism)'
    xmlOutputFlag: '--xunit-xml-output=$(${{ parameters.buildOutputLocationVar }})/test-results.xml'
    shardFlags: '--num-shards=$(System.TotalJobsInPhase);--run-shard=$(System.JobPositionInPhase)'
    litFlags: '$(fixedFlags);$(parallelismFlag);$(xmlOutputFlag);$(shardFlags)'
  strategy:
    parallel: ${{ parameters.numShards }}
  timeoutInMinutes: 360
  steps:
    - download: current
      artifact: '${{ parameters.targetPlatform }}-$(System.JobPositionInPhase)-tests'
      displayName: DownloadPipelineArtifactTests
    - task: CmdLine@2
      displayName: 'Run Tests'
      timeoutInMinutes: 120
      condition: succeeded()
      - template: vcpkg-dependencies.yml
        parameters:
          targetPlatform: ${{ parameters.targetPlatform }}
      - template: cmake-configure-build.yml
        parameters:
          targetPlatform: ${{ parameters.targetPlatform }}
          hostArch: ${{ parameters.hostArch }}
          targetArch: ${{ parameters.vsDevCmdArch }}
          cmakeAdditionalFlags: '-DTESTS_RUN_ONLY=ON'
      - template: run-tests.yml
        parameters:
          hostArch: ${{ parameters.hostArch }}
          targetPlatform: ${{ parameters.targetPlatform }}
          targetArch: ${{ parameters.vsDevCmdArch }}
          displayName: 'Build Tests'
          publishArtifact: true
